# Generated by Django 5.2.7 on 2025-10-22 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_tareas'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareas',
            name='tareaRealizada',
            field=models.BooleanField(default=False),
        ),
    ]
